### ISSUE TITLE
Can you add reference to RFC/I-D in the README?

### ISSUE THREAD

**Issue by Neustradamus** [ogrebgr/scram-sasl#10]
@ogrebgr: I wish you a Happy New Year!

Can you add reference to RFC/I-D in the README?
- https://datatracker.ietf.org/doc/html/rfc7677
- https://datatracker.ietf.org/doc/html/draft-melnikov-scram-sha-512

Thanks in advance.

**Comment by ogrebgr** [comment]
I am afraid that the only applicable RFC is 5802

**Comment by Neustradamus** [comment]
@ogrebgr: Please remove comments in the bad ticket, sorry I was done a bad tag...

In the README:
```
Java library that implements SCRAM SASL (RFC5802) for both server and client.

Includes SHA-1, SHA-256, SHA-512 implementations and examples (you can easily create implementation that uses your own hashing function and digest).
```

It is:
- RFC5802
- RFC7677
- draft-melnikov-scram-sha-512

You can add that TLS Binding is not supported, no -PLUS variants in the README (with a better sentence).

Note: There is a ticket for TLS Binding and for other SCRAM like SHA3-512.

**Comment by Neustradamus** [comment]
@ogrebgr: Do you understand me?
