### ISSUE TITLE
Unable to build (Bintray)

### ISSUE THREAD

**Issue by dbrimley** [ogrebgr/scram-sasl#2]
Hi
I've tried running gradle but build fails because of this file...

`https://github.com/ogrebgr/scram-sasl/blob/master/lib/bintray-config.gradle` which expects your personal version of `apply from: '/home/ogre/.signing/bintray-config.gradle'`

I'm kind of new to bintray and gradle, do I need my own bintray config file?

**Comment by ogrebgr** [comment]
Hi,
Just delete the content of the bintray-config.gradle and you should be able to build. It is needed only for publishing the jars on bintray. I have to find a way to fix this issue.

**Comment by ogrebgr** [comment]
Just pushed a fix. Please pull and you will be able to build.
