### ISSUE TITLE
Bug in com.bolyartech.scram_sasl.server.AbstractScramSaslServerProcessor#onMessage

### ISSUE THREAD

**Issue by vsevols** [ogrebgr/scram-sasl#5]
Hello! I've found a bug. Your examples are working because of recursive call onMessage -> handleClientFirst -> onUserDataLoaded -> MyToClientSender.sendMessage -> onMessage 

If we return from onMessage before receiving next message from client then mState is set to State.WAITING_FOR_USER_DATA  instead of State.SERVER_FIRST_SENT which causes failure on next onMessage call.

`diff --git a/StormDrafts/lib/scram-sasl/lib/src/main/java/com/bolyartech/scram_sasl/server/AbstractScramSaslServerProcessor.java b/StormDrafts/lib/scram-sasl/lib/src/main/java/com/bolyartech/scram_sasl/server/AbstractScramSaslServerProcessor.java
index ce9bc46..0a858ab 100644
--- a/StormDrafts/lib/scram-sasl/lib/src/main/java/com/bolyartech/scram_sasl/server/AbstractScramSaslServerProcessor.java
+++ b/StormDrafts/lib/scram-sasl/lib/src/main/java/com/bolyartech/scram_sasl/server/AbstractScramSaslServerProcessor.java
@@ -115,7 +115,7 @@ abstract class AbstractScramSaslServerProcessor implements ScramSaslServerProces
             switch (mState) {
                 case INITIAL:
                     if (handleClientFirst(message)) {
-                        mState = State.WAITING_FOR_USER_DATA;
+                        //mState = State.WAITING_FOR_USER_DATA;
                     } else {
                         mState = State.ENDED;
                         notifyFail();`

**Comment by ogrebgr** [comment]
Hi,
Why (and how) would you "If we return from `onMessage` before receiving next message"?
Anyway, when the user data is loaded `onUserDataLoaded()` will be called, which will send first server message and switch to SERVER_FIRST_SENT, so when the next client message arrives, it will be handled correctly.
The only way to exit `onMessage` prematurely is user data loader to throw an runtime exception.
Please elaborate.

**Comment by vsevols** [comment]
My code:

```
public void my_authorize() throws InvalidUserNamePasswordException{

        ScramSaslServerProcessor processor = new ScramSha256SaslServerProcessor(
                0,
                listener,
                loader,
                sender
        );

        while (!processor.isEnded())
       		processor.onMessage(ioHandler.readChunk().stringContent()));

if(!getAuthorized())
            throw new InvalidUserNamePasswordException();
}
```


Note that processor.onMessage is called ONLY from my_authorize() method and not called recursive (as this do mock MyToClientSender.sendMessage -> onMessage) from itself.

1. First onMessage call  in loop of my_authorize:
case INITIAL:
1.1 calling handleClientFirst => loadUserData => onUserDataLoaded{... mState = State.SERVER_FIRST_SENT ...} //<- this is right state
1.2 and right after calling handleClientFirst in onMessage body: mState = State.WAITING_FOR_USER_DATA
1.3 onMessage exits

2. Second onMessage call in loop of my_authorize:
```
case WAITING_FOR_USER_DATA:
                    mState = State.ENDED;
                    notifyFail();
```

**Comment by ogrebgr** [comment]
Basically the problem here is that the second message from the client comes before the server is able to send the first server message. Are you reading the data with `ioHandler.readChunk()` from some stream/file?

**Comment by vsevols** [comment]
https://www.dropbox.com/t/y7NixGuEdONetyua
See modified example ScramSha256Example.java : running server in other thread, not in the client's thread.
It fails to authorize if "bugFix" field set to false

**Comment by ogrebgr** [comment]
I still think that you are using it in a weird way. Probably it would be best if you fork the repo. Thank you for the bug report anyway.
