### ISSUE TITLE
Publish on maven central

### ISSUE THREAD

**Issue by laeubi** [ogrebgr/scram-sasl#8]
It would be useful to have a release of this on maven central.

**Comment by ircnet-com** [comment]
Thank you for the great library!

Please let me know when the project is on maven central, so I can remove my fork.

**Comment by ogrebgr** [comment]
@ircnet-com 
Hi,
Last time I've tried 2-3 years ago it was real pain to register a project there so I gave up. Did they enhanced their system to be more convenient?

**Comment by ircnet-com** [comment]
Hi,
I never did it so far. But since almost all dependencies are there, it should be straight forward :)
btw. jcenter will be shut down soon, see https://bintray.com/bintray/jcenter

Greetings
Patrick

**Comment by ogrebgr** [comment]
Just published version 2.0.2 on maven central

**Comment by ogrebgr** [comment]
Just published version 2.0.2 on maven central
