### ISSUE TITLE
Can you add topics in this repository?

### ISSUE THREAD

**Issue by Neustradamus** [ogrebgr/scram-sasl#9]
@ogrebgr: I wish you a Happy New Year!

Can you add in this repository, topics?
- scram
- scram-sha-1
- scram-sha-256
- scram-sha-512

Thanks in advance.

**Comment by ogrebgr** [comment]
Done. Thank you for the suggestion

**Comment by Neustradamus** [comment]
@ogrebgr: Thanks for this searching improvement! :)
